1 SELECT ProductName AS Name
  FROM Products

2 SELECT * FROM CUSTOMERS AS CLIENT

3 SELECT PRODUCTNAME 
  FROM PRODUCTS
  UNION
  SELECT PRODUCTNAME 
  FROM PRODUCTS_DISCOUNTED;

4 SELECT PRODUCTNAME
  FROM PRODUCTS 
  INTERSECT
  SELECT PRODUCTNAME
  FROM PRODUCTS_DISCOUNTED

5 SELECT DISTINCT FIRSTNAME, COUNTRY
    FROM CUSTOMERS

6 SELECT ProductName, 
         StockQuantity,
         IIF(StockQuantity > 100, 'YES', 'NO') AS INSTOCK	
  FROM Products_Discounted;

7 SELECT ProductName
  FROM Products
  UNION
  SELECT ProductName
  FROM Products_Discounted

8
