1 SELECT ProductName AS Name
  FROM Products

2 SELECT * FROM CUSTOMERS AS CLIENT

3 SELECT PRODUCTNAME 
  FROM PRODUCTS
  UNION
  SELECT PRODUCTNAME 
  FROM PRODUCTS_DISCOUNTED;

4 SELECT PRODUCTNAME
  FROM PRODUCTS 
  INTERSECT
  SELECT PRODUCTNAME
  FROM PRODUCTS_DISCOUNTED

5 SELECT DISTINCT FIRSTNAME, COUNTRY
    FROM CUSTOMERS

6 SELECT ProductName, Price,
CASE 
  WHEN Price > 1000 THEN 'HIGH'
  ELSE 'LOW'
  END AS PriceCategory
  FROM Products  

7 SELECT ProductName, 
         StockQuantity,
         IIF(StockQuantity > 100, 'YES', 'NO') AS INSTOCK	
  FROM Products_Discounted;

8 SELECT ProductName
  FROM Products
  UNION
  SELECT ProductName
  FROM Products_Discounted

9 SELECT ProductName
  FROM PRODUCTS
  EXCEPT
  SELECT ProductName
  FROM Products_Discounted;

10 SELECT 
    PRICE,
		 IIF(PRICE > 1000, 'EXPENSIVE', 'AFFORDABLE')  AS PRICECATEGORY
  FROM PRODUCTS;

11 SELECT FirstName, Age, Salary FROM EMPLOYEES
   WHERE AGE < 25 OR SALARY > 60000

12 UPDATE EMPLOYEES
   SET SALARY = SALARY * 1.10
   WHERE DEPARTMENTNAME = 'HR' OR EMPLOYEEID = 5;

13 SELECT SALEAMOUNT,
   CASE
    WHEN SALEAMOUNT > 500
    THEN 'TOPTIER'
    WHEN SALEAMOUNT BETWEEN 200 AND 500 
    THEN 'MID TIER' 
    ELSE 'LOW TIER'
    END AS CATEGORY
FROM SALES;

14 SELECT CUSTOMERID
   FROM Orders
   EXCEPT 
   SELECT CUSTOMERID
   FROM SALES; 

15 SELECT CUSTOMERID, QUANTITY,
   CASE 
     WHEN QUANTITY = 1 THEN '3%'
     WHEN QUANTITY BETWEEN 1 AND 3 THEN '5%'
     ELSE '7%'
  END AS DISCOUNT_PERCENTAGE
  FROM ORDERS;
