CREATE TABLE EMPLOYEES (EMPID INT, NAME VARCHAR (50), SALARY DECIMAL (10,2))
SELECT * FROM EMPLOYEES
INSERT INTO EMPLOYEES (EMPID, NAME, SALARY) VALUES
(1, 'JOHN', 120000.00),
(2, 'ANDREW', 130000.00),
(3, 'JACK', 150000.00);
UPDATE EMPLOYEES
SET SALARY = 7000
WHERE EMPID = 1
DELETE EMPLOYEES
WHERE EMPID = 2
Delete - Removes specific rows from a table based on a condition. Can be rolled back (if within a transaction). Table structure remains.
Truncate - Removes all rows from a table quickly, without logging individual row deletions. Cannot be rolled back in some DBMSs. Table structure remains.
Drop - Deletes the entire table, including its structure. Cannot be rolled back.
ALTER TABLE EMPLOYEES
ALTER COLUMN NAME VARCHAR (100)
ALTER TABLE EMPLOYEES
ADD DEPARTMENT VARCHAR(50)
ALTER TABLE EMPLOYEES
ALTER COLUMN SALARY FLOAT
CREATE TABLE DEPARTMENTS (DEPARTMENTID INT PRIMARY KEY, DEPARTMENTNAME VARCHAR(50));
SELECT * FROM DEPARTMENTS
SELECT * FROM EMPLOYEES
DELETE FROM EMPLOYEES

INSERT INTO DEPARTMENTS (DEPARTMENTID, DEPARTMENTNAME)
SELECT 1, 'HUMAN RESOURES' UNION ALL
SELECT 2, 'FINANCE' UNION ALL
SELECT 3, 'IT' UNION ALL
SELECT 4, 'MARKETING' UNION ALL
SELECT 5, 'LOGISTICS'
UPDATE EMPLOYEES
SET DEPARTMENT = 'MANAGEMENT'
WHERE SALARY > 50000;
DELETE FROM EMPLOYEES;
ALTER TABLE EMPLOYEES
DROP COLUMN DEPARTMENT;
EXEC sp_rename 'EMPLOYEES', 'STAFFMEMBERS';
DROP TABLE DEPARTMENTS;
CREATE TABLE PRODUCTS (
PRODUCTID INT PRIMARY KEY,
PRODUCTNAME VARCHAR, 
CATEGORY VARCHAR, 
PRICE DECIMAL
);
SELECT * FROM PRODUCTS
ALTER TABLE PRODUCTS 
ADD CONSTRAINT CHECK_PRICE_GREATER_THAN_ZERO
CHECK(PRICE>0);
ALTER TABLE PRODUCTS
ADD STOCKQUANTITY INT DEFAULT 50;

EXEC sp_rename 'PRODUCTS.CATEGORY', 'PRODUCTCATEGORY', 'COLUMN';
INSERT INTO PRODUCTS (PRODUCTID, PRODUCTNAME, PRODUCTCATEGORY, PRICE, STOCKQUANTITY)
VALUES
(1, 'LAPTOP', 'ELECTRONICS', 1200.00, 10), 
(2, 'DESKCHAIR', 'FURNITURE', 150.00, 25),
(3, 'NOTEBOOK', 'STATIONERY', 3.50, 200),
(4, 'SMARTPHONE', 'ELECTRONICS', 850.00, 15),
(5, 'PENCIL', 'STATIONERY', 9.00, 100);
EXEC sp_help 'PRODUCTS';
ALTER TABLE PRODUCTS
ALTER COLUMN PRODUCTNAME VARCHAR(50);
ALTER TABLE PRODUCTS 
ALTER COLUMN PRODUCTCATEGORY VARCHAR(50);
INSERT INTO PRODUCTS (PRODUCTID, PRODUCTNAME, PRODUCTCATEGORY, PRICE, STOCKQUANTITY)
VALUES
(1, 'LAPTOP', 'ELECTRONICS', 1200.00, 10), 
(2, 'DESKCHAIR', 'FURNITURE', 150.00, 25),
(3, 'NOTEBOOK', 'STATIONERY', 3.50, 200),
(4, 'SMARTPHONE', 'ELECTRONICS', 850.00, 15),
(5, 'PENCIL', 'STATIONERY', 9.00, 100);
SELECT *
INTO PRODUCTS_BACKUP
FROM PRODUCTS;
SELECT * FROM PRODUCTS_BACKUP
EXEC sp_rename 'PRODUCTS', 'INVENTORY';
ALTER TABLE INVENTORY
DROP CONSTRAINT CHECK_PRICE_GREATER_THAN_ZERO
ALTER TABLE INVENTORY
ALTER COLUMN PRICE FLOAT
SELECT * FROM INVENTORY
ALTER TABLE INVENTORY
ADD PRODUCTCODE INT IDENTITY(1000, 5);



