1 SELECT PRODUCTS.PRODUCTNAME,
       SUPPLIERS.SUPPLIERNAME
  FROM PRODUCTS
  CROSS JOIN SUPPLIERS

2 SELECT DEPARTMENTS.DEPARTMENTNAME,
       EMPLOYEES.NAME 
	   FROM 
	   DEPARTMENTS
	   CROSS JOIN 
	   EMPLOYEES;

3 SELECT PRODUCTS.PRODUCTNAME, SUPPLIERS.SUPPLIERNAME
  FROM PRODUCTS
  INNER JOIN SUPPLIERS ON PRODUCTS.SUPPLIERID = SUPPLIERS.SUPPLIERID;

4 SELECT CUSTOMERS.FIRSTNAME, CUSTOMERS.LASTNAME,
       ORDERS.ORDERID
	   FROM ORDERS	
	   INNER JOIN CUSTOMERS ON ORDERS.CUSTOMERID = CUSTOMERS.CUSTOMERID;

5 SELECT STUDENTS.NAME, 
       COURSES.COURSENAME
	   FROM STUDENTS
	   CROSS JOIN COURSES

6 SELECT PRODUCTS.PRODUCTNAME, PRODUCTS.PRODUCTID,
       ORDERS.ORDERID
	   FROM PRODUCTS
	   INNER JOIN ORDERS ON PRODUCTS.PRODUCTID = ORDERS.PRODUCTID;

7 SELECT EMPLOYEES.NAME,
       EMPLOYEES.EMPLOYEEID,
	   DEPARTMENTS.DEPARTMENTID,
	   DEPARTMENTS.DEPARTMENTNAME
	   FROM EMPLOYEES
	   INNER JOIN DEPARTMENTS ON EMPLOYEES.DEPARTMENTID = DEPARTMENTS.DEPARTMENTID
	   ORDER BY DEPARTMENTID;

8 SELECT STUDENTS.NAME AS STUDENTNAME,
       ENROLLMENTS.COURSEID
	   FROM STUDENTS
	   INNER JOIN ENROLLMENTS ON STUDENTS.STUDENTID = ENROLLMENTS.STUDENTID

9 SELECT ORDERS.ORDERID,
       PAYMENTS.PAYMENTID
	   FROM ORDERS
	   INNER JOIN PAYMENTS ON ORDERS.ORDERID = PAYMENTS.ORDERID

10 SELECT ORDERS.ORDERID,
       ORDERS.PRODUCTID,
	   PRODUCTS.PRODUCTNAME,
	   PRODUCTS.PRICE
	   FROM PRODUCTS
	   INNER JOIN ORDERS ON PRODUCTS.PRODUCTID = ORDERS.PRODUCTID
	   WHERE PRICE > 100;

11 SELECT EMPLOYEES.NAME,
       DEPARTMENTS.DEPARTMENTNAME,
	   EMPLOYEES.DEPARTMENTID,
	   DEPARTMENTS.DEPARTMENTID
	   FROM EMPLOYEES
	   CROSS JOIN DEPARTMENTS
	   WHERE EMPLOYEES.DEPARTMENTID <> DEPARTMENTS.DEPARTMENTID

12 SELECT ORDERS.ORDERID,
       ORDERS.PRODUCTID,
	   ORDERS.QUANTITY,
	   PRODUCTS.PRODUCTNAME,
	   PRODUCTS.STOCKQUANTITY
	   FROM ORDERS
	   INNER JOIN PRODUCTS ON PRODUCTS.PRODUCTID = ORDERS.PRODUCTID
	   WHERE PRODUCTS.STOCKQUANTITY < ORDERS.QUANTITY

13 
