1 SELECT PRODUCTS.PRODUCTNAME,
       SUPPLIERS.SUPPLIERNAME
  FROM PRODUCTS
  CROSS JOIN SUPPLIERS

2 SELECT DEPARTMENTS.DEPARTMENTNAME,
       EMPLOYEES.NAME 
	   FROM 
	   DEPARTMENTS
	   CROSS JOIN 
	   EMPLOYEES;

3 SELECT PRODUCTS.PRODUCTNAME, SUPPLIERS.SUPPLIERNAME
  FROM PRODUCTS
  INNER JOIN SUPPLIERS ON PRODUCTS.SUPPLIERID = SUPPLIERS.SUPPLIERID;

4 SELECT CUSTOMERS.FIRSTNAME, CUSTOMERS.LASTNAME,
       ORDERS.ORDERID
	   FROM ORDERS	
	   INNER JOIN CUSTOMERS ON ORDERS.CUSTOMERID = CUSTOMERS.CUSTOMERID;

5 SELECT STUDENTS.NAME, 
       COURSES.COURSENAME
	   FROM STUDENTS
	   CROSS JOIN COURSES

6 SELECT PRODUCTS.PRODUCTNAME, PRODUCTS.PRODUCTID,
       ORDERS.ORDERID
	   FROM PRODUCTS
	   INNER JOIN ORDERS ON PRODUCTS.PRODUCTID = ORDERS.PRODUCTID;

7 SELECT EMPLOYEES.NAME,
       EMPLOYEES.EMPLOYEEID,
	   DEPARTMENTS.DEPARTMENTID,
	   DEPARTMENTS.DEPARTMENTNAME
	   FROM EMPLOYEES
	   INNER JOIN DEPARTMENTS ON EMPLOYEES.DEPARTMENTID = DEPARTMENTS.DEPARTMENTID
	   ORDER BY DEPARTMENTID;

8 SELECT STUDENTS.NAME AS STUDENTNAME,
       ENROLLMENTS.COURSEID
	   FROM STUDENTS
	   INNER JOIN ENROLLMENTS ON STUDENTS.STUDENTID = ENROLLMENTS.STUDENTID

9 SELECT ORDERS.ORDERID,
       PAYMENTS.PAYMENTID
	   FROM ORDERS
	   INNER JOIN PAYMENTS ON ORDERS.ORDERID = PAYMENTS.ORDERID

10 SELECT ORDERS.ORDERID,
       ORDERS.PRODUCTID,
	   PRODUCTS.PRODUCTNAME,
	   PRODUCTS.PRICE
	   FROM PRODUCTS
	   INNER JOIN ORDERS ON PRODUCTS.PRODUCTID = ORDERS.PRODUCTID
	   WHERE PRICE > 100;

11 SELECT EMPLOYEES.NAME,
       DEPARTMENTS.DEPARTMENTNAME,
	   EMPLOYEES.DEPARTMENTID,
	   DEPARTMENTS.DEPARTMENTID
	   FROM EMPLOYEES
	   CROSS JOIN DEPARTMENTS
	   WHERE EMPLOYEES.DEPARTMENTID <> DEPARTMENTS.DEPARTMENTID

12 SELECT ORDERS.ORDERID,
       ORDERS.PRODUCTID,
	   ORDERS.QUANTITY,
	   PRODUCTS.PRODUCTNAME,
	   PRODUCTS.STOCKQUANTITY
	   FROM ORDERS
	   INNER JOIN PRODUCTS ON PRODUCTS.PRODUCTID = ORDERS.PRODUCTID
	   WHERE PRODUCTS.STOCKQUANTITY < ORDERS.QUANTITY

13 SELECT CUSTOMERS.CUSTOMERID,
	       CUSTOMERS.FIRSTNAME,
		   CUSTOMERS.LASTNAME,
		   SALES.PRODUCTID,
		   SALES.SALEAMOUNT
		   FROM SALES
		   INNER JOIN CUSTOMERS ON SALES.CUSTOMERID = CUSTOMERS.CUSTOMERID
		   WHERE SALEAMOUNT >= 500;
	
14 SELECT
       ENROLLMENTS.STUDENTID,
	   STUDENTS.NAME AS STUDENTNAME,
	   COURSES.COURSENAME
	   FROM ENROLLMENTS
	   INNER JOIN STUDENTS ON STUDENTS.STUDENTID = ENROLLMENTS.STUDENTID
	   INNER JOIN COURSES ON ENROLLMENTS.COURSEID = COURSES.COURSEID

15 SELECT Products.PRODUCTNAME,
	       SUPPLIERS.SUPPLIERNAME
		   FROM SUPPLIERS
		   INNER JOIN PRODUCTS ON SUPPLIERS.SUPPLIERID = PRODUCTS.SUPPLIERID
		   WHERE SUPPLIERNAME LIKE '%TECH%';

16 SELECT O.ORDERID,
       O.TOTALAMOUNT,
	   P.PAYMENTID,
	   P.AMOUNT
	   FROM ORDERS O
	   INNER JOIN PAYMENTS P ON O.ORDERID = P.ORDERID
	   WHERE P.AMOUNT < O.TOTALAMOUNT

17 SELECT E.NAME AS EMP_NAME,
	       D.DEPARTMENTNAME
		   FROM EMPLOYEES E
		   INNER JOIN DEPARTMENTS D ON E.DEPARTMENTID = D.DEPARTMENTID
18 SELECT P.PRODUCTNAME,
       C.CATEGORYNAME
	   FROM PRODUCTS P
	   INNER JOIN CATEGORIES C ON P.CATEGORY = C.CATEGORYNAME
	   WHERE C.CATEGORYNAME IN('ELECTRONICS', 'FURNITURE');

19   SELECT SALES.SALEID,
	          CUSTOMERS.FIRSTNAME,
			  CUSTOMERS.LASTNAME,
			  CUSTOMERS.COUNTRY
			  FROM CUSTOMERS
			  INNER JOIN SALES ON CUSTOMERS.CUSTOMERID = SALES.CUSTOMERID
			  WHERE CUSTOMERS.COUNTRY = 'USA';

20 SELECT ORDERS.ORDERID,
       ORDERS.TOTALAMOUNT,
       CUSTOMERS.FIRSTNAME,
	   CUSTOMERS.LASTNAME,
	   CUSTOMERS.COUNTRY
	   FROM CUSTOMERS
	   INNER JOIN ORDERS ON CUSTOMERS.CUSTOMERID = CUSTOMERS.CUSTOMERID
	   WHERE CUSTOMERS.COUNTRY = 'GERMANY'
	   AND ORDERS.TOTALAMOUNT > 100;

21 
SELECT 
    E1.EmployeeID AS Employee1_ID,
    E1.Name AS Employee1_Name,
    E1.DepartmentID AS Department1,
    E2.EmployeeID AS Employee2_ID,
    E2.Name AS Employee2_Name,
    E2.DepartmentID AS Department2
FROM 
    Employees E1
INNER JOIN 
    Employees E2 ON E1.EmployeeID < E2.EmployeeID 
WHERE 
    E1.DepartmentID <> E2.DepartmentID;

22 
	  
