1 SELECT MIN(PRICE) AS min_price
FROM PRODUCTS

2 SELECT MAX(SALARY) AS MAX_SALARY
FROM EMPLOYEES

3 SELECT COUNT(*) AS TOTAL_CUSTOMERS
FROM CUSTOMERS

4 SELECT COUNT(DISTINCT CATEGORY) AS UNIQUE_CATEGORIES
FROM PRODUCTS

5 SELECT SUM(SALEAMOUNT) AS TOTALAMOUNT
FROM SALES
WHERE PRODUCTID = 7;

6 SELECT AVG(AGE) AS AVGAGE
FROM EMPLOYEES

7 SELECT DepartmentNAME, COUNT(*) AS EmployeeCount
FROM Employees
GROUP BY DepartmentNAME;

8 SELECT 
  CATEGORY, 
MIN(PRICE) AS MINPRICE, 
MAX(PRICE) AS MAXPRICE
FROM PRODUCTS
GROUP BY CATEGORY;

9 SELECT CUSTOMERID, 
  SUM(SALEAMOUNT) AS TOTAL_FOR_PERCLIENT
FROM SALES
GROUP BY CUSTOMERID;

10 SELECT 
    DepartmentName, 
    COUNT(DepartmentName) AS Employees_Count
FROM 
    Employees
GROUP BY 
    DepartmentName
HAVING  
    COUNT(DepartmentName) > 5;

11 
		SELECT PRODUCTID,
		SUM(SALEAMOUNT) AS TOTAL,
		AVG(SALEAMOUNT) AS AVERAGE
		FROM SALES
		GROUP BY PRODUCTID;

12 SELECT COUNT(*) AS TOTAL_EMP_IN_HR
FROM EMPLOYEES
WHERE DEPARTMENTNAME = 'HR';

13 SELECT DEPARTMENTNAME, 
MAX(SALARY) AS THE_HIGHEST_SALARY, 
MIN(SALARY) AS THE_LOWEST_SALARY
FROM EMPLOYEES
GROUP BY DEPARTMENTNAME

14 SELECT DEPARTMENTNAME, AVG(SALARY) AS AVG_SALARY
FROM EMPLOYEES
GROUP BY DEPARTMENTNAME;

15 SELECT DEPARTMENTNAME, 
AVG(SALARY) AS AVG_SALARY, 
COUNT(*) EMP_COUNT
FROM EMPLOYEES
GROUP BY DEPARTMENTNAME;

16 SELECT 
    Category,
    AVG(Price) AS AveragePrice
FROM 
    Products
GROUP BY 
    Category
HAVING 
    AVG(Price) > 400;

17 SELECT 
    YEAR(SaleDate) AS SaleYear,
    SUM(SaleAmount) AS TotalSales
FROM 
    Sales
GROUP BY 
    YEAR(SaleDate)
ORDER BY 
    SaleYear;

18 SELECT CustomerID, COUNT(*) AS OrdersCount
FROM Sales
GROUP BY CustomerID
HAVING COUNT(*) >= 3;

19 SELECT DEPARTMENTNAME, AVG(SALARY) AS AVGSALALRY
	FROM EMPLOYEES
	GROUP BY DEPARTMENTNAME
	HAVING AVG(SALARY) > 60000;

20 SELECT CATEGORY, AVG(PRICE) AVG_PRICE
	FROM PRODUCTS
	GROUP BY CATEGORY
	HAVING AVG(PRICE) > 150;

21 SELECT CUSTOMERID,SUM(SALEAMOUNT) TOTAL_SALES
	FROM SALES
	GROUP BY CUSTOMERID
	HAVING SUM(SALEAMOUNT) > 1500;

22 SELECT DEPARTMENTNAME, 
	   SUM(SALARY) AS TOTAL,
	   AVG(SALARY) AS AVERAGE
    FROM EMPLOYEES 
	GROUP BY DEPARTMENTNAME
	HAVING AVG(SALARY) > 65000;

23 
  
24 SELECT  
      YEAR(ORDERDATE) AS ORDERYEAR, 
      MONTH(ORDERDATE) AS ORDERMONTH,
      SUM(TOTALAMOUNT) AS TOTALSALES, 
	  COUNT(DISTINCT PRODUCTID) AS UNIQUEPRODUCTS
FROM ORDERS
GROUP BY YEAR(ORDERDATE), MONTH(ORDERDATE)
HAVING COUNT(DISTINCT PRODUCTID) >= 2;

25 SELECT  
   YEAR(ORDERDATE) AS ORDERYEAR,
   MIN(QUANTITY) AS MIN_QTY,
   MAX(QUANTITY) AS MAX_QTY
   FROM ORDERS
   GROUP BY YEAR(ORDERDATE);
