1  SELECT CATEGORY, 
          SUM(STOCKQUANTITY) AS TOTAL_STOCK
   FROM PRODUCTS
   GROUP BY CATEGORY;

2 SELECT AVG(PRICE) AS AVGPRICE
  FROM PRODUCTS
  WHERE CATEGORY = 'ELECTRONICS';

3 SELECT FIRSTNAME, CITY 
  FROM CUSTOMERS
  WHERE CITY LIKE 'L%';

4 SELECT PRODUCTNAME 
  FROM PRODUCTS
  WHERE PRODUCTNAME LIKE '%ER';

5 SELECT FIRSTNAME, COUNTRY 
  FROM CUSTOMERS
  WHERE COUNTRY LIKE '%A';

6 SELECT MAX(PRICE) AS THE_HIGHEST_PRICED
  FROM PRODUCTS;

7 SELECT 
    PRODUCTNAME, 
	STOCKQUANTITY,
CASE
   WHEN STOCKQUANTITY < 30 THEN 'LOW STOCK' 
   ELSE 'SUFFICIENT'
   END AS STOCK_STATUS
   FROM PRODUCTS;

8 SELECT COUNTRY, COUNT(CUSTOMERID) AS TOTAL_CUSTOMERS
   FROM CUSTOMERS
   GROUP BY COUNTRY;

9 SELECT 
     MAX(QUANTITY) AS MAX_QTY_ORDERED, 
	 MIN(QUANTITY) AS MIN_QTY_ORDERED
 FROM ORDERS;

10

11 SELECT PRODUCTNAME
   FROM PRODUCTS
   UNION ALL
   SELECT PRODUCTNAME
   FROM Products_Discounted;

12 SELECT PRODUCTNAME
  FROM PRODUCTS
  UNION
  SELECT PRODUCTNAME
  FROM Products_Discounted;

13 SELECT 
  YEAR(ORDERDATE) AS ORDER_YEAR,
  AVG(TOTALAMOUNT) AS AVG_AMOUNT
  FROM ORDERS
  GROUP BY YEAR(ORDERDATE);

14  SELECT PRODUCTNAME, PRICE,
 CASE
  WHEN PRICE < 100 THEN 'LOW'
  WHEN PRICE BETWEEN 100 AND 500 THEN 'MID'
  ELSE 'HIGH'
  END AS PRICEGROUP
  FROM PRODUCTS;

15  
