1  SELECT CATEGORY, 
          SUM(STOCKQUANTITY) AS TOTAL_STOCK
   FROM PRODUCTS
   GROUP BY CATEGORY;

2 SELECT AVG(PRICE) AS AVGPRICE
  FROM PRODUCTS
  WHERE CATEGORY = 'ELECTRONICS';

3 SELECT FIRSTNAME, CITY 
  FROM CUSTOMERS
  WHERE CITY LIKE 'L%';

4 SELECT PRODUCTNAME 
  FROM PRODUCTS
  WHERE PRODUCTNAME LIKE '%ER';

5 SELECT FIRSTNAME, COUNTRY 
  FROM CUSTOMERS
  WHERE COUNTRY LIKE '%A';

6 SELECT MAX(PRICE) AS THE_HIGHEST_PRICED
  FROM PRODUCTS;

7 SELECT 
    PRODUCTNAME, 
	STOCKQUANTITY,
CASE
   WHEN STOCKQUANTITY < 30 THEN 'LOW STOCK' 
   ELSE 'SUFFICIENT'
   END AS STOCK_STATUS
   FROM PRODUCTS;

8 SELECT COUNTRY, COUNT(CUSTOMERID) AS TOTAL_CUSTOMERS
   FROM CUSTOMERS
   GROUP BY COUNTRY;

9 SELECT 
     MAX(QUANTITY) AS MAX_QTY_ORDERED, 
	 MIN(QUANTITY) AS MIN_QTY_ORDERED
 FROM ORDERS;

10

11 SELECT PRODUCTNAME
   FROM PRODUCTS
   UNION ALL
   SELECT PRODUCTNAME
   FROM Products_Discounted;

12 SELECT PRODUCTNAME
  FROM PRODUCTS
  UNION
  SELECT PRODUCTNAME
  FROM Products_Discounted;

13 SELECT 
  YEAR(ORDERDATE) AS ORDER_YEAR,
  AVG(TOTALAMOUNT) AS AVG_AMOUNT
  FROM ORDERS
  GROUP BY YEAR(ORDERDATE);

14  SELECT PRODUCTNAME, PRICE,
 CASE
  WHEN PRICE < 100 THEN 'LOW'
  WHEN PRICE BETWEEN 100 AND 500 THEN 'MID'
  ELSE 'HIGH'
  END AS PRICEGROUP
  FROM PRODUCTS;

15  SELECT * FROM
         (
	 SELECT DISTRICT_ID, DISTRICT_NAME, POPULATION, YEAR
	 FROM CITY_POPULATION
	 )
	 AS SOURCETABLE
    PIVOT (SUM(POPULATION)
       FOR YEAR IN([2012], [2013])
       ) AS PIVOTTABLE;

16  SELECT PRODUCTID, 
	   SUM(SALEAMOUNT) AS TOTAL_SALES
	   FROM SALES
       GROUP BY PRODUCTID;

17 SELECT PRODUCTNAME
	   FROM PRODUCTS
	   WHERE PRODUCTNAME LIKE '%OO%';
 SELECT * 
	   INTO POPULATION_EACH_CITY
	   FROM ( SELECT DISTRICT_NAME, POPULATION, YEAR
              FROM CITY_POPULATION)
			  AS SOURCETABLE
	 PIVOT (
	        SUM(POPULATION)
	        FOR DISTRICT_NAME IN ([BEKTEMIR], [CHILONZOR], [YAKKASAROY], [MIROBOD], [YASHNOBOD])
			)
			AS PIVOTTABLE;

18    SELECT * INTO POPULATION_EACH_CITY
	   FROM
	   (SELECT YEAR, DISTRICT_NAME, POPULATION
	    FROM CITY_POPULATION
	    WHERE DISTRICT_NAME IN('BEKTEMIR', 'CHILONZOR', 'YAKKASAROY')
	   )
            AS SOURCETABLE
      PIVOT (
             SUM(POPULATION)
	     FOR DISTRICT_NAME IN([BEKTEMIR], [CHILONZOR], [YAKKASAROY])
	    )
             AS PIVOTTABLE;

19 SELECT TOP 3
CUSTOMERID, SUM(TOTALAMOUNT) AS TOTALSPENT
FROM INVOICES
GROUP BY CUSTOMERID
ORDER BY TOTALSPENT DESC;

20 SELECT *
   FROM POPULATION_EACH_YEAR
   UNPIVOT (
         POPULATION FOR YEAR IN([2012], [2013])
	   ) AS UNPVT
	     ORDER BY CAST(YEAR AS INT), DISTRICT_ID;

21 SELECT
   PRODUCTS.PRODUCTNAME,
   COUNT(SALES.SALEID) AS TIMES_SOLD
FROM PRODUCTS
INNER JOIN SALES ON PRODUCTS.PRODUCTID = SALES.PRODUCTID
GROUP BY PRODUCTNAME;

22 SELECT DISTRICT_NAME,
       POPULATION,
	   YEAR
	   FROM (SELECT YEAR, BEKTEMIR, CHILONZOR, YAKKASAROY FROM POPULATION_EACH_CITY) AS SOURCETABLE
	   UNPIVOT(
	         POPULATION FOR DISTRICT_NAME IN(BEKTEMIR, CHILONZOR, YAKKASAROY))
			 AS PIVOTEDTABLE





